import express from 'express';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createAuth} from './auth.mjs';
import {createLibrary} from '../server/library-core.mjs';
const at=process.argv.indexOf('--config');if(at<0)throw Error('Usage: node app/main.mjs --config /private/config.json');
const configFile=path.resolve(process.argv[at+1]);const settings=JSON.parse(fs.readFileSync(configFile));
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const prefix=new URL(settings.public_url).pathname.replace(/\/$/,'');
const app=express();app.disable('x-powered-by');app.set('trust proxy','loopback');
app.use((req,res,next)=>{res.set({'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' https: blob:; media-src https: blob:; connect-src 'self' https:; frame-src https:; frame-ancestors 'none'; base-uri 'none'; form-action 'self'"});next();});
app.get(prefix+'/healthz',(req,res)=>res.json({ok:true,version:'1.0.0'}));
const api=express.Router();api.use(express.json({limit:'256kb'}));
const auth=createAuth(path.join(path.dirname(configFile),'accounts.json'),settings);auth.register(api);
const core=createLibrary(api,configFile);await core.ready;
api.get('/nodes/:id',auth.admin,async(req,res)=>{try{res.json(await core.worker(req.params.id,'/healthz'));}catch{res.status(502).json({error:'节点不可用。'});}});
api.post('/nodes/:id',auth.admin,async(req,res)=>{try{res.json(await core.worker(req.params.id,'/settings',req.body));}catch{res.status(409).json({error:'应用失败：请检查配置或等待节点活跃任务结束。'});}});
for(const method of ['get','post'])api[method]('/nodes/:id/egress/:site',auth.admin,async(req,res)=>{try{res.json(await core.worker(req.params.id,'/egress/'+req.params.site,method==='post'?req.body:undefined));}catch{res.status(409).json({error:'出口不可用或正在被任务使用。'});}});
api.get('/policy',auth.admin,async(req,res)=>{try{res.json({desired_days:core.config.retention_days||7,gcs:await core.storage().retention(),nodes:await Promise.all(core.config.import_workers.map(async n=>({id:n.id,...await core.worker(n.id,'/settings')})))});}catch{res.status(502).json({error:'无法核对全部存储保留策略。'});}});
api.post('/policy',auth.admin,async(req,res)=>{try{const days=req.body.days;if(!Number.isInteger(days)||days<1||days>30)throw Error();for(const n of core.config.import_workers){const h=await core.worker(n.id,'/healthz');if(h.active)throw Error();}await core.storage().retention(days);for(const n of core.config.import_workers)await core.worker(n.id,'/settings',{retention_seconds:days*86400});core.config.retention_days=days;fs.writeFileSync(configFile+'.tmp',JSON.stringify(core.config,null,2),{mode:0o600});fs.renameSync(configFile+'.tmp',configFile);res.json({ok:true,message:'期望策略已保存。copyparty 定时应用器会在空闲时应用，请刷新核对实际值。'});}catch{res.status(409).json({error:'未能全部应用，请刷新实际策略并检查节点或桶权限。'});}});
app.use(prefix+'/api',api);
const assets=['library-ui.js','settings.js','media.js','upload.js','style.css'];for(const name of assets)app.get(prefix+'/'+name,(req,res)=>res.sendFile(path.join(root,name)));
app.get(prefix+'/jquery.js',(req,res)=>res.sendFile(path.join(root,'node_modules/jquery/dist/jquery.min.js')));
app.use(prefix,express.static(path.join(root,'app/public'),{index:'index.html',dotfiles:'deny'}));
app.get(prefix,(req,res)=>res.redirect(prefix+'/'));
app.use((err,req,res,next)=>res.status(400).json({error:'请求无效。'}));
const server=app.listen(settings.app_port||3930,'127.0.0.1',()=>console.info('File Library 1.0.0 ready'));
process.on('SIGTERM',()=>{core.close();server.close(()=>process.exit());});
